/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4_sia;
import java.awt.BorderLayout;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Григорий, Pahomov Dmitry
 */
public class mainJFrame extends javax.swing.JFrame {


    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();

        this.updateImage();
    }

    public void changeImage(String newImageFileName) {
        ii = new ImageIcon(newImageFileName);
        imageLabel = new JLabel(ii);
        jScrollPane1.setViewportView(imageLabel);
        return;
    }

    public void changeImage(byte[] newImage) {
        ii = new ImageIcon(newImage);
        imageLabel = new JLabel(ii);
        jScrollPane1.setViewportView(imageLabel);
        return;
    }

    public void updateImage() {
        byte[] img_stream = this.RunDot(this.myTree.getDotScript());
        if(img_stream!=null) {
            this.changeImage(img_stream);
        }
        return;
    }

    /**
     * Run dot.exe with given script.
     * @param script is dot-script to execute.
     * @return status of dot execution.
     */
    private byte[] RunDot(String script) {

        byte[] img_stream = null;
        Runtime r = Runtime.getRuntime();
        Process p;
        try {
            p = r.exec(new String[] {"dot", "-Tpng"});
            InputStream err = p.getErrorStream();
            InputStream out = p.getInputStream();
            OutputStream in = p.getOutputStream();

            in.write(script.getBytes());
            in.close();

            if (err.available() != 0) {
                byte[] errmsg = new byte[err.available()];
                err.read(errmsg);
                throw new Throwable(new String(errmsg));
            }

            err.close();
            p.waitFor();

            img_stream = new byte[out.available()];
            out.read(img_stream);

        } catch (Throwable ex) {
            System.err.printf(ex.getLocalizedMessage());
        }

        return img_stream;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueJTextField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        fiendJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        valueJTextField.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N

        addJButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        fiendJButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        fiendJButton.setText("Find");
        fiendJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiendJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valueJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fiendJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJButton)
                    .addComponent(fiendJButton)
                    .addComponent(deleteJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        myTree.remove(valueJTextField.getText());
        this.updateImage();
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        myTree.add(valueJTextField.getText());
        this.updateImage();
    }//GEN-LAST:event_addJButtonActionPerformed

    private void fiendJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiendJButtonActionPerformed
        JOptionPane.showMessageDialog(null, myTree.contains(valueJTextField.getText())?"finded":"not finded");
    }//GEN-LAST:event_fiendJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JButton fiendJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField valueJTextField;
    // End of variables declaration//GEN-END:variables
    private ImageIcon ii;
    private JLabel imageLabel;
    private PSet<String> myTree = new PSet<String>();
}
